services:
  - type: web
    name: prueba-tecnica-enegence
    env: php
    buildCommand: "composer install && php artisan migrate --force"
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: COPOMEX_TOKEN
        value: pruebas
